# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fe1a7f2611f09175afa223eaa7598b372916423c8da5f3ab5f0de71252899f77e5e2ad2dff9a26ec53de9f6b98b451d67efd30038464f7a6ef04ff6ace4e34a

test:
  secret_key_base: d2e298d3287f86d34df5c2e2860162b561bfd9c9bd9d54b74027e14c685e52279832d1c7d5a42089e5281b7fbf3ef701318ff611b8c15dbc01b01e064b050dfe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
